# Generated by Django 2.2.5 on 2019-12-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('must_prereg', models.BooleanField()),
                ('event_description', models.CharField(max_length=200)),
                ('registration_fee', models.PositiveIntegerField()),
                ('number_players_min', models.PositiveIntegerField()),
                ('number_players_max', models.PositiveIntegerField()),
                ('day_or_night', models.CharField(max_length=200)),
                ('mini_category', models.CharField(max_length=200)),
                ('first_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('third_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_name', models.CharField(max_length=200)),
                ('organization_abbrv', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=9)),
                ('student_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=6)),
                ('student_email', models.CharField(max_length=200)),
                ('student_contact_no', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Organization')),
            ],
            options={
                'unique_together': {('student_number', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('signature', models.BooleanField()),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Scoresheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_rank', models.PositiveIntegerField()),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Signatures'),
        ),
        migrations.AddField(
            model_name='event',
            name='student_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consensus_revision', models.TextField()),
                ('consensus_reason', models.TextField()),
                ('time_stamp_created', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
                ('signature_list_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Signatures')),
            ],
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addendum_revision', models.TextField()),
                ('addendum_reason', models.TextField()),
                ('time_stamp_created', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('signature_list_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Signatures')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('time_stamp_created', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='main.Student')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep', to='main.Student')),
                ('signature_list_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Signatures')),
            ],
            options={
                'unique_together': {('event_name', 'representative', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('activity_date', models.DateField()),
                ('activity_time_start', models.TimeField()),
                ('activity_time_end', models.TimeField()),
                ('activity_venue', models.CharField(max_length=200)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
            ],
            options={
                'unique_together': {('event_name', 'activity')},
            },
        ),
    ]
